### ISSUE TITLE
Don't close this issue without answering please

### ISSUE THREAD

**Issue by RealHeha** [Jameison-Tech/BackdoorDiscordBot#2]
The error I get says 
[Error: ENOENT: no such file or directory, scandir 'C:\Users\alimi\Desktop\stuff\Other stuff\Youtubebruh\Discord Backdoor\commands'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\alimi\\Desktop\\stuff\\Other stuff\\Youtubebruh\\Discord Backdoor\\commands'
}
C:\Users\alimi\Desktop\stuff\Other stuff\Youtubebruh\Discord Backdoor\bot.js:15
        let jsFiles = files.filter(f => f.split(".").pop() === "js");
                            ^

TypeError: Cannot read property 'filter' of undefined
    at C:\Users\alimi\Desktop\stuff\Other stuff\Youtubebruh\Discord Backdoor\bot.js:15:22
    at FSReqCallback.oncomplete (fs.js:171:23)

**Comment by ghost** [comment]
He gave up on this about 3 months ago, i dont think you will get an answer any time soon

**Comment by RealHeha** [comment]
> He gave up on this about 3 months ago, i dont think you will get an answer any time soon

Damn, thanks for the reply.
